### ISSUE TITLE
comma operator hides failed results

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#1]
In function
```
void End(bool failed, clock_t duration) {
 this->failed = failed, this->duration = duration;
  }
```
the ',' must be a ';', so it reads:
```
void End(bool failed, clock_t duration) {
 this->failed = failed;
 this->duration = duration;
  }
```
otherwise the function is doing same as:
```
void End(bool failed, clock_t duration) {
 this->failed = failed;
 this->duration = duration;
 this->failed = this->duration;
  }
```
will do.

**Comment by zhangzheheng12345** [comment]
Sorry, it's my fault. I didn't have a deep understanding to this syntax.

Issue fixed. Close.

**Comment by modem-man-gmx** [comment]
You are welcome! This is a very special syntax, born around the year 1975 for C. While it is often seen in declarations like
```
int a=0, b=1;
```
almost all C/C++ developers avoid using it in statements, because it is looking the same but doing different there.
In some very rare cases it can be helpful to remember its existence: complicated macros to override existing code without editing it.
