### ISSUE TITLE
Feature Request: rework SetConsoleTextAttribute() to SetConsoleMode() + ANSI-Sequences

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#13]
Regarding SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), winColor) ...

This kind of Windows Console Color Codes are subject to stopped support in some (midterm) future.
Please take a look into [the outdating warming](https://learn.microsoft.com/en-us/windows/console/setconsoletextattribute)

Looks like MicroSoft goes a step towards Linux/Unix behaviour (or just reactivates old MS-DOS 4.01 ANSI-sequences via a new API), read here: [how to rework](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)

Ready-to-adopt sample code is on the page, just search for "wprintf(L"\x1b[31mThis text has a red foreground using SGR.31.\r\n");"

Anyway, there is no urgency in doing this right now.

**Comment by zhangzheheng12345** [comment]
OK I know that. This should be changed.

But currently I cannot reach my Windows PC for some time (school's started), so please provide a PR if you like. I won't add those codes unless I have really tested them on Windows.

**Comment by zhangzheheng12345** [comment]
Hi there! This is fixed in the latest version of v1.5.3.

Issue closed.

**Comment by modem-man-gmx** [comment]
Hi,
thank you for the fix and for the notification.

Recently I am involved in many hours of extra work at my daytime job, so I hope to continue my project in October or so.

⁣Yours,
Mo
​
