### ISSUE TITLE
nonzero return value on FAILED tests required

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#2]
Your main function should return kind of `this->failed` flag.
Why?
Almost every Unittest framework does it for automatic evaluation from scripts, automake tools or (with increasingly importance) from github actions.

Currently, you always return 0 from main, regardless if all test went fine or if one or more failed.
Minimum request is to return 0 on OK, 1 on FAILED.
More helpful would be the total amount of failures.

```
int main(int argn, char* argc[]) {
  // Offer arn & argc for CONFIG
  ...
  lightest::globalRegisterData.RunRegistered();
  // Optionally print the default outputs
  if (lightest::toOutput) {
    lightest::globalRegisterData.testData->PrintSons();
  }
  ...
  return 0;
}
```

I tried to find a quick way, but in case is set lightest::toOutput = false, there is no failure counting at all. Could be helpful to have a "summing up failures" function, based on the same evaluation also done by `globalRegisterData.testData->PrintSons()`

I'd like to propose a change like:

```
int main(int argn, char* argc[]) {
  int overall_failure = 0;
  // Offer arn & argc for CONFIG
  ...
  lightest::globalRegisterData.RunRegistered();
  // Optionally print the default outputs
  if (lightest::toOutput) {
    lightest::globalRegisterData.testData->PrintSons();
  }
  overall_failure = lightest::globalRegisterData.testData->Sumup_Failures();
  ...
  return overall_failure;
}
```
Of course with some additional provision to not becoming 0 on increment overflow beyond MAX_INT (or perhaps beyond 255 if target is MicroSoft Runtime for Windows).

**Comment by zhangzheheng12345** [comment]
Yeah I've thought of this before, and for some reason I didn't add this feature.
I'll reconsider adding this feature.

**Comment by zhangzheheng12345** [comment]
I've fixed this by the recent commit which was carelessly marked as fixing issue #3, forgive me about that.

I make main function returns 1 if there are failed tests, no matter how many. I think user can count the number of failed tests through DATA or other data processing tools provided in the future. I've also edited test.cpp to give an example.

If you agree with this change you can give an positive reply and close this issue.

**Comment by modem-man-gmx** [comment]
good next steps, but there are two bugs introduced:

1. an failure will now report all tests as failed
2. an failure will still return 0 in main, because invisible at the root object.

I will not open an issue, because I am trying to fix it and send pull request.

**Comment by modem-man-gmx** [comment]
Failure 1 of comment from above is fixed with the second "nasty comma" fix from Sarge, I made a Pull Request from it.
