### ISSUE TITLE
cosmetically: nice up the report time

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#3]
Very low issue:
´´´
void Print() const {
    PrintTabs();
    ...
    SetColor(Color::Reset);
  //cout << TimeToMs(duration) << "ms" << endl;
    cout << " " << TimeToMs(duration) << "ms" << endl;
  }
´´´
this extra space would make the default colored output much more eye-friendly

**Comment by zhangzheheng12345** [comment]
Same as issue #4, and has been fixed. Close.
