### ISSUE TITLE
cosmetically: incorrect scientific notation for elapsed time

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#4]
Sorry for being annoying ;-) 

At some places you missed a space between numerical value and physical unit. It is scientific incorrect writing (except for °C and °F) to have the unit following the numerical without space.

one is here:
```
void Print() const {
    PrintTabs();
    ...
  //cout << TimeToMs(duration) << "ms" << endl; // hard to read and incorrect notion
    cout << " " << TimeToMs(duration) << " ms" << endl;
  }
```

the other here:

```
int main(int argn, char* argc[]) {
  ...
//std::cout << "Done. " << lightest::TimeToMs(clock()) << "ms used." // incorrect notion
  std::cout << "Done. " << lightest::TimeToMs(clock()) << " ms used."
            << std::endl;
  return 0;
}
```

Sorry for not sending pull requests or .patch files - I'm sitting with my family in the living room and have only limited access to my big development PC.

**Comment by zhangzheheng12345** [comment]
Got that. I'll fix this.

**Comment by zhangzheheng12345** [comment]
Issue fixed. Close.
