### ISSUE TITLE
Bug: wrong counting of failed tests

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#8]
Hi zhangzheheng12345,

the marking of only the failed tests as "FAIL" and the anyway passed tests as "PASS" does not work, as well as the overall result.

As requested by you, I made a neutral test.cpp (instead of noprintf's test).
Could you please take it by checking out https://github.com/modem-man-gmx/Lightest/tree/upstream_integration ?

This is basically your origin/head, but I put some very simple of my tests in.
Expectations:
- Compiling with `-DFAIL=0` must result in all 6 tests passed and summary result == passed, main return 0.
- Compiling with `-DFAIL=1` must result in 1 test failed and summary result == failed, main return >0.

I did not tried to adopt your CMake file, because I never used CMake. But you could take my legacy `Makefile` from root folder. Whatever you prefer.
Anyway, the recent origin/head does not fulfill this simple rules. It always reports all tests failing

To locate the problem, I replaced the lightest.h step by step with your older commits. You know, at some point I had also to remove `failedTestCount` from `DATA(GetFailedTests)`.

So I found the last good working is:
```
SHA-1: 90bc58d5a116b7d2f7b32eaa0cf7a7b809d753f0

* Fix issue #1
```
Here the expectations are met.

All commits after this one broke the correct evaluation of the overall result.

Yours sincerely,
Mo

**Comment by zhangzheheng12345** [comment]
Emmm I'm a little bit confused now...

So is this issue related to your PR? 

And I use Repl.it to show you some things. [Lightest origin](https://replit.com/@zhangzheheng123/Lightest) and [Lightest Yours](https://@zhangzheheng123/Lightest-1). One is mine and one is yours, but I added some uncommitted changes, just as the solution I've described in PR #7 . 

For my one, it shows the solution to solve the problem you showed in PR #7 . And for your one I applied same changes as I've done in my one, and found that those dirty hacks are not needed, yet **you expectation still not reach**. **I don't understand, why, why, why `PrintFinal` reports FAIL, which means `finalFailed` is `true`, but it returns 0???**

**Comment by modem-man-gmx** [comment]
Just for your information: My "dirty fix" does also not work in all cases.
I had a series ob 3 completely independent subs, where tests failed in sub A and sub B + C is okay since days, but at least C got also marked as failed. After repairing the test in sub A, all tests passed.
Hmmm... crazy stuff.

You had one question I did not answered so far, regarding actively reporting error.

Think of pseudo code:
```
class A;
class B;

A.list<B> childs = B[10];
 
for( auto son : A.childs );
   son.function(...);
```

3 ways of information transfer:
1. report via asking the son: `son.function(); result |= son.GetFailed();` this is recent.
2. report via return value `result |= son.function();` this is one proposal, you did not like.
3. `son.function(..., this);` and inside ```void B::function(..., A& parent) { bool res = do_tst(...); parent.reportMyFailure(res); }```

I think, I used some strongly German language influenced sentence. My English is sometimes a bit "Germanized". The sample in number 3 should be self-explaining.

**Comment by zhangzheheng12345** [comment]
I got what you mean I think. But the first seems to a better abstraction. If you use the second, then you have to put failuring collecting in to the registerer. Registerer should be for CONFIG, TEST, and DATA, while failure is only for tests, so put it into registerer is extra I think. (Any misunderstanding or mistakes and ignorance of situation you can just point them out directly, I might not be as experienced as you)

To be honest, I didn't feel your English is German-like. Anyway as long as communication is fluent, there's no other extra requirement. Perhaps I'm also sometimes a bit using Chinglish.

**Comment by modem-man-gmx** [comment]
Working well since
SHA-1: 54468fba09070cadad7762d9bb496f5101ae7982
* Merge fix into dev

Many thanks!
