### ISSUE TITLE
unexpected "const" on stack objects?

### ISSUE THREAD

**Issue by modem-man-gmx** [zhangzheheng12345/Lightest#9]
When using the TEST() and SUB() like a so-called "fixture", I observe unexpected compiler error, even with this very, very reduced test.

```
#ifndef DIM
#define DIM(a) (sizeof(a)/sizeof(a[0])) // calculate real dimension of plain-C-array
#endif

TEST( Check_Some_printf )
{
  // having data here works like a fixture for all following SUB() calls
  int c = -1;
  int d = 0;
  char Required[128];

  snprintf( Required, DIM(Required), "A) Minus1_c=%d, Zero_d=%d.", c, d );
  Required[ DIM(Required)-1 ] = '\0';

  SUB( Align_default_fill_default )
  {
    REQ( std::string( Required ), ==, std::string( "A) Minus1_c=-1, Zero_d=0." ) );
    REQ( std::string( Required ), !=, std::string( "A) Minus1_c=-1.0, Zero_d=00." ) );
  };

  // SUB( more_tests_wish_same_data ) { ... }
  // SUB( plenty_of_further_tests_wish_same_data ) { ... }
}
```

gives:

```
test_lightest/test_runner_lt1.cpp: In lambda function:
test_lightest/test_runner_lt1.cpp:488:15: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
  488 |     snprintf( Required, DIM(Required), "A) Minus1_c=%d, Zero_d=%d.", c, d );
      |               ^~~~~~~~
      |               |
      |               const char*
include/stdio.h:451:21: note:   initializing argument 1 of 'int snprintf(char*, size_t, const char*, ...)'
  451 | int snprintf (char *__stream, size_t __n, const char *__format, ...)
      |               ~~~~~~^~~~~~~~
```

This comes likely from inside the lambda, but I am not very familiar with the pro & con of lambda tricks and workarounds
:-(

**Comment by modem-man-gmx** [comment]
Please note:
This is only meant to inform you about this behavior. Could help when implementing "fixtures".

The following change made my code working for my test needs (again very, very reduced). The need to have one fixture was not high, because I can do further processing on same data set within the SUB instead spread over all subs:

```
#ifndef DIM
#define DIM(a) (sizeof(a)/sizeof(a[0])) // calculate real dimension of plain-C-array
#endif

TEST( Check_Some_printf )
{
  // having const data here works like a fixture, but non-const are not accepted.
  int c = -1;
  int d = 0;

  SUB( Align_default_fill_default )
  {
    // having non-const data here works like at least a bit a fixture between the REQ() calls 
    char Required[128];
    snprintf( Required, DIM(Required), "A) Minus1_c=%d, Zero_d=%d.", c, d );
    Required[ DIM(Required)-1 ] = '\0';

    REQ( std::string( Required ), ==, std::string( "A) Minus1_c=-1, Zero_d=0." ) );
    REQ( std::string( Required ), !=, std::string( "A) Minus1_c=-1.0, Zero_d=00." ) );
  };

  // SUB( more_tests_with_other_data ) { ... }
  // SUB( plenty_of_further_tests_with_other_data ) { ... }
}
```

**Comment by zhangzheheng12345** [comment]
I think the first example should be like this:

```C++
#ifndef DIM
#define DIM(a) (sizeof(a)/sizeof(a[0])) // calculate real dimension of plain-C-array
#endif

TEST( Check_Some_printf )
{
  // having data here works like a fixture for all following SUB() calls
  int c = -1;
  int d = 0;
  char Required[128];

  SUB( Align_default_fill_default )
  {
    snprintf( Required, DIM(Required), "A) Minus1_c=%d, Zero_d=%d.", c, d );
    Required[ DIM(Required)-1 ] = '\0';
    REQ( std::string( Required ), ==, std::string( "A) Minus1_c=-1, Zero_d=0." ) );
    REQ( std::string( Required ), !=, std::string( "A) Minus1_c=-1.0, Zero_d=00." ) );
  };

  // SUB( more_tests_wish_same_data ) { ... }
  // SUB( plenty_of_further_tests_wish_same_data ) { ... }
}
```

Yes fixture are const because while catching outside variables in lambda function I use const capture.

```C++
// const capture:
[=](){ ... };
// changeable capture: (caution for the life cycle, outside variables with shorter life cycle than lambda may cause runtime error)
[&](){ ... };
```

This is partially because I'm influenced by some functional programming thoughts and I don't think variables in fixture should be changed. Besides, it's necessary, for sub tests are run when the test function has already returned, which means outside variables are destroyed and not available. Only const capture won't cause runtime error. You can define a class wrapping shared variables in the function and get an instance in every sub test.

**Comment by zhangzheheng12345** [comment]
Addition: another quick fix to this is declare those shared variables as static, but this is only a temporary solution, for it will cause unnecessary RAM use.

**Comment by modem-man-gmx** [comment]
Regarding the `[=]{...}` vs.  `[&]{...}`, thank you for the refresh! I even knew that before, but have since forgotten it. Used too seldom in million lines of mixed C99, C++03 and C++17 code in my daytime job. =:-)

The variant with having only the declaration outside the sub still makes `const Required[128]` ;-)

Anyway, I don't have a problem with this situation. Can use either the static or the code-repeating workarounds, because at worst my REQ() are depending on the previous' REQ()'s data. Want say, recently there is no need for relationship across SUB()s. And if I need it, I could do the static trick, because I don't need the deepest feature of the 'Fixture' any time soon: isolation between different TEST() sets. So there is no urgency in having full featured fixtures.

Conclusion:
You could either close this issue, or you could take it as "future feature request for fixtures".

Some further thoughts:
Some other unit test libraries are packing the tests as member functions into classes, so they can easily offer FIXTURE_DECLARE (just a block without curly braces after ´private:´), FIXTURE_INIT (block inside Constructor) and FIXTURE_SHUTDOWN (Destructor). But this would insert plenty of object pointers, perhaps even vtable pointers, and could be one reason why their tests are slower compared to Lightest.

You surely already know, that a class can also have multiple scope labels and duplicated curls, so it looks like this:
```
class runner {
public:
  runner() {{FIXTURE_INIT};prepare_internals();}
  ~runner() {{FIXTURE_SHUTDOWN};}
private:
  prepare_internals() {...}
private:
  FIXTURE_DECLARE
private:
  int own_data; ...
}
```
I don't remember where I saw this kind of, used too many Test Driven Development libraries till today. But I would bet, many of them are using this approach.
So I am very curious about your way of fixture implementation...

Off-topic:
I am positively surprised you mentioned the `static`, because I knew a very few programmers which know this quite legacy trick. At best they use this keyword inside a class. Outside, they rather use it on global scope variables (redundant). So I see, you take the C++ learning very seriously compared with other, even business-experienced programmers. That's cool!

There are some more tricks with `static` when building programs made from multiple .o-files and want to play with visibility, but this is more a C90 thing, so even I hardly remember the details.

Have a nice day,
Mo
